version: 1

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/trading_system.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  strategy_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/strategy.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  monitoring_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/monitoring.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  security_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/security.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  performance_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/performance.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  src.agents:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  src.strategies:
    level: INFO
    handlers: [console, file, strategy_file, error_file]
    propagate: no

  src.monitoring:
    level: INFO
    handlers: [console, file, monitoring_file, error_file]
    propagate: no

  src.core.safety_checker:
    level: INFO
    handlers: [console, file, security_file, error_file]
    propagate: no

  src.web:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  src.data:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  src.execution:
    level: INFO
    handlers: [console, file, error_file]
    propagate: no

  tests:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file, error_file]